# Generated by Django 3.0.8 on 2020-08-02 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACMMEMBER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('None', 'Choose an option'), ('CSE BAO', 'CSE BAO'), ('CSE AIML', 'CSE AIML'), ('CSE CCVT', 'CSE CCVT'), ('CSE CSF', 'CSE CSF'), ('CSE IT-INFRA', 'CSE IT-INFRA')], default='None', max_length=100)),
                ('year', models.CharField(choices=[('None', 'Choose your Year'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='None', max_length=20)),
                ('dob', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919939799264'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919939799264'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sap_id', models.CharField(max_length=9)),
                ('hostel_pg', models.TextField()),
                ('membership_type', models.CharField(choices=[('None', 'Choose an option'), ('Premium (4 Years + 1 Year International)', 'Premium (4 Years + 1 Year International)'), ('Standard (2 Years)', 'Standard (2 Years)'), ('Basic (1 Year)', 'Basic (1 Year)')], default='None', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
