# Generated by Django 3.0.8 on 2020-08-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_acmmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmmember',
            old_name='user',
            new_name='member',
        ),
    ]
