# Generated by Django 3.0.8 on 2020-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200803_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='None', max_length=20, null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
