# Generated by Django 3.0.8 on 2020-08-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guestuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestuser',
            old_name='email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='guestuser',
            old_name='name',
            new_name='guest_name',
        ),
    ]
