# Generated by Django 3.0.8 on 2020-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_membershiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
