# Generated by Django 3.0.8 on 2020-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_membershiptype_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
