# Generated by Django 3.0.8 on 2020-08-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200806_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='amount',
        ),
    ]
