# Generated by Django 3.0.8 on 2020-08-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_membershiptype_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipType',
        ),
    ]
