# Generated by Django 3.0.8 on 2020-08-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_membershiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmmember',
            name='membership_type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='accounts.MembershipType'),
        ),
    ]
